name = "corepapers"
compatibility_date = "2026-05-26"
pages_build_output_dir = "dist/public"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "corepapers"
database_id = "4d4e6fcc-d498-4896-a93c-cee8d6d0af14"

# Keep the R2 binding in the Cloudflare dashboard unless you want to manage it here too.
